spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyectochad
    username: postgres
    password: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: file:./uploads/
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080
  address: 0.0.0.0
